server:
  port: 9900

spring:
  application:
    name: spring-cloud-eureka

eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

